/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Entities.*;
import static Interface.PlayGame.*;
import static Interface.UserLogin.*;
import Methods.Methods;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Game extends javax.swing.JFrame {

    Methods met = new Methods();

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        jPanel2.hide();
        jPanel3.hide();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCharacters = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fuego.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 160, 160));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agua.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 160, 160));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tierra.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 160, 160));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/viento.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 160, 160));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Fire");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Water");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Ground");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Wind");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Select the image with the tipe of your arena");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jButton11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton11.setText("Exit");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 120, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tumblr_static_tumblr_static_bnjo0hdhm1kcw84k4sw84owo0_640-iloveimg-resized.gif"))); // NOI18N
        jLabel46.setText("          ");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 450));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("Characters");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 22, -1, -1));

        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("Team1 Area");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 63, -1, -1));

        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("Team 2 Area");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 63, -1, -1));

        jTableCharacters.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTableCharacters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "0", "1", "2", "3", "XXXXXXX", "XXXXXXX", "6", "7", "8", "9"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableCharacters);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 95, 530, 188));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("Team 1");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 292, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("Team 2");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 294, -1, -1));

        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("Characters");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 322, 80, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("Add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        jButton10.setText("Continue");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 90, -1));

        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("0");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 123, 10, -1));

        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("1");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 143, 10, 10));

        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("2");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 159, 40, 10));

        jLabel38.setForeground(new java.awt.Color(204, 204, 204));
        jLabel38.setText("3");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 173, 40, -1));

        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setText("4");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 187, 40, -1));

        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setText("5");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 203, 20, -1));

        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("6");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 221, 20, 10));

        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("7");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 237, 20, 10));

        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setText("8");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 253, 30, 10));

        jLabel44.setForeground(new java.awt.Color(204, 204, 204));
        jLabel44.setText("9");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 263, 20, 20));

        jLabel45.setForeground(new java.awt.Color(204, 204, 204));
        jLabel45.setText("Characters");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 322, 63, -1));

        jComboBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 120, -1));

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 120, -1));

        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Batt.jpg"))); // NOI18N
        jLabel47.setText("  ");
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -3, 790, 460));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Towers");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 23, 88, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 51));
        jLabel16.setText("Team1 Area");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 63, -1, -1));

        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setText("Team 2 Area");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 63, -1, -1));

        jTable2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "0", "1", "2", "3", "XXXXXXX", "XXXXXXX", "6", "7", "8", "9"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 95, 530, 188));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Team 1");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 292, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Team 2");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 294, -1, -1));

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Positions");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 327, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 352, 40, -1));

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 352, 40, -1));

        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Positions");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 327, -1, -1));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 352, 40, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 352, 40, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 388, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 388, -1, -1));

        jButton7.setText("Play");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 407, 77, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("0");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 123, 10, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setText("1");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 143, 10, 10));

        jLabel11.setForeground(new java.awt.Color(0, 0, 51));
        jLabel11.setText("2");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 159, 40, 10));

        jLabel12.setForeground(new java.awt.Color(0, 0, 51));
        jLabel12.setText("3");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 173, 40, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("4");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 187, 40, -1));

        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("5");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 203, 20, -1));

        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setText("6");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 221, 20, 10));

        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setText("7");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 237, 20, 10));

        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setText("8");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 253, 30, 10));

        jLabel22.setForeground(new java.awt.Color(0, 0, 51));
        jLabel22.setText("9");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 263, 20, 20));

        jLabel23.setForeground(new java.awt.Color(0, 0, 51));
        jLabel23.setText("X");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 103, 14, -1));

        jLabel24.setForeground(new java.awt.Color(0, 0, 51));
        jLabel24.setText("Y");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 75, 14, -1));

        jLabel25.setText("X");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 356, 14, -1));

        jLabel26.setText("Y");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 356, 14, -1));

        jLabel27.setText("X");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 356, 14, -1));

        jLabel28.setText("Y");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 356, 14, -1));

        jLabel48.setForeground(new java.awt.Color(0, 0, 51));
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/kingdom_under_fire_2_03_2560x1600.jpg"))); // NOI18N
        jLabel48.setText("           ");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 460));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -3, 790, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Arena arena = new Arena("ground");
        UsersBackup.getArenas().add(arena);
        jPanel1.hide();
        jPanel3.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Arena arena = new Arena("wind");
        UsersBackup.getArenas().add(arena);
        jPanel1.hide();
        jPanel3.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Arena arena = new Arena("fire");
        UsersBackup.getArenas().add(arena);
        jPanel1.hide();
        jPanel3.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Arena arena = new Arena("water");
        UsersBackup.getArenas().add(arena);
        jPanel1.hide();
        jPanel3.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if ((player1.TowersList.isEmpty() == true) || (player2.TowersList.isEmpty() == true)) {
            JOptionPane.showMessageDialog(null, "You need to create 1 tower for team1 and 1 for team2");
        } else {
            jTextField1.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
            jTextField4.setText(null);
            jPanel2.hide();
            jPanel1.show();

            UserLogin.PlayGameInterface.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel model4 = (DefaultTableModel) jTablePlay.getModel();

        if ((jTextField1.getText().equals("")) || (jTextField2.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "YOU CAN'T leave the space in blank");
        } else {
            try {
                int i = Integer.parseInt(jTextField1.getText());
                int j = Integer.parseInt(jTextField2.getText());

                if (matriz[i][j] == null) {
                    if ((i == 0) || (i <= 9)) {
                        if ((j == 0) || (j <= 3)) {
                            Towers t = new Towers();
                            player1.TowersList.add(t);
                            matriz[i][j] = t;
                            if (model.getValueAt(i, j) == null) {
                                model.setValueAt("T", i, j);
                                model4.setValueAt("T", i, j);

                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "You can´t put negatives numbers o the numbers of the other side of the arena");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "You can´t put negatives numbers o more than 9");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "You can't put the tower there, because there is another element");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "You can't put letters");
            } catch (ArrayIndexOutOfBoundsException e2) {
                JOptionPane.showMessageDialog(null, "You can't put more numbers, respect the size of the gmae table");
            }
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel model4 = (DefaultTableModel) jTablePlay.getModel();

        if ((jTextField3.getText().equals("")) || (jTextField4.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "YOU CAN'T leave the space in blank");
        } else {
            try {
                int i = Integer.parseInt(jTextField3.getText());
                int j = Integer.parseInt(jTextField4.getText());

                if (matriz[i][j] == null) {
                    if ((i == 0) || (i <= 9)) {
                        if ((j >= 6) || (j == 9)) {
                            Towers t = new Towers();
                            player2.TowersList.add(t);
                            matriz[i][j] = t;
                            if (model.getValueAt(i, j) == null) {
                                model.setValueAt("T", i, j);
                                model4.setValueAt("T", i, j);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "You can´t put negatives numbers o the numbers of the other side of the arena");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "You can´t put negatives numbers o more than 9");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "You can't put the tower there, because there is another element");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "You can't put letters");
            } catch (ArrayIndexOutOfBoundsException e2) {
                JOptionPane.showMessageDialog(null, "You can't put more numbers, respect the size of the gmae table");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel) jTableCharacters.getModel();
        DefaultTableModel model3 = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel model4 = (DefaultTableModel) jTablePlay.getModel();

        String Name = jComboBox1.getSelectedItem() + "";

        if (UserLogin.Methods.ReturnChacarterGround(Name) != null) {
            if (player2.groundCharactersList.contains(UserLogin.Methods.ReturnChacarterGround(Name))) {
                JOptionPane.showMessageDialog(null, "It have player 2");
                return;
            } else {
                if (player1.groundCharactersList.contains(UserLogin.Methods.ReturnChacarterGround(Name))) {
                    JOptionPane.showMessageDialog(null, "It have player 1");
                    return;
                } else {
                    GroundCharacter g = UserLogin.Methods.ReturnChacarterGround(Name);

                    int i = 3;
                    int i2 = 4;
                    int i3 = 5;
                    int j = 0;

                    if (model2.getValueAt(i, j) == null) {
                        model2.setValueAt("G", i, j);
                        model3.setValueAt("G", i, j);
                        model4.setValueAt("G", i, j);
                        matriz[i][j] = g;
                        jTableCharacters.locate(i, j).setForeground(Color.RED);
                        player1.groundCharactersList.add(g);
                    } else if (model2.getValueAt(i2, j) == null) {
                        model2.setValueAt("G", i2, j);
                        model3.setValueAt("G", i2, j);
                        model4.setValueAt("G", i2, j);
                        matriz[i2][j] = g;
                        jTableCharacters.locate(i2, j).setForeground(Color.RED);
                        player1.groundCharactersList.add(g);
                    } else if (model2.getValueAt(i3, j) == null) {
                        model2.setValueAt("G", i3, j);
                        model3.setValueAt("G", i3, j);
                        model4.setValueAt("G", i3, j);
                        matriz[i3][j] = g;
                        jTableCharacters.locate(i3, j).setForeground(Color.RED);
                        player1.groundCharactersList.add(g);
                    }
                }
            }
        }
        if (UserLogin.Methods.ReturnChacarterFire(Name) != null) {
            if (player2.fireCharactersList.contains(UserLogin.Methods.ReturnChacarterFire(Name))) {
                JOptionPane.showMessageDialog(null, "It have player 2");
                return;
            } else {
                if (player1.fireCharactersList.contains(UserLogin.Methods.ReturnChacarterFire(Name))) {
                    JOptionPane.showMessageDialog(null, "It have player 1");
                    return;
                } else {
                    FireCharacter g = UserLogin.Methods.ReturnChacarterFire(Name);

                    int i = 3;
                    int i2 = 4;
                    int i3 = 5;
                    int j = 0;

                    if (model2.getValueAt(i, j) == null) {
                        model2.setValueAt("F", i, j);
                        model3.setValueAt("F", i, j);
                        model4.setValueAt("F", i, j);
                        matriz[i][j] = g;
                        jTableCharacters.locate(i, j).setForeground(Color.RED);
                        player1.fireCharactersList.add(g);
                    } else if (model2.getValueAt(i2, j) == null) {
                        model2.setValueAt("F", i2, j);
                        model3.setValueAt("F", i2, j);
                        model4.setValueAt("F", i2, j);
                        matriz[i2][j] = g;
                        jTableCharacters.locate(i2, j).setForeground(Color.RED);
                        player1.fireCharactersList.add(g);
                    } else if (model2.getValueAt(i3, j) == null) {
                        model2.setValueAt("F", i3, j);
                        model3.setValueAt("F", i3, j);
                        model4.setValueAt("F", i3, j);
                        matriz[i3][j] = g;
                        jTableCharacters.locate(i3, j).setForeground(Color.RED);
                        player1.fireCharactersList.add(g);
                    }
                }
            }
        }
        if (UserLogin.Methods.ReturnChacarterWater(Name) != null) {
            if (player2.waterCharactersList.contains(UserLogin.Methods.ReturnChacarterWater(Name))) {
                JOptionPane.showMessageDialog(null, " It have player 2");
                return;
            } else {
                if (player1.waterCharactersList.contains(UserLogin.Methods.ReturnChacarterWater(Name))) {
                    JOptionPane.showMessageDialog(null, "It have player 1");
                    return;
                } else {
                    WaterCharacter g = UserLogin.Methods.ReturnChacarterWater(Name);

                    int i = 3;
                    int i2 = 4;
                    int i3 = 5;
                    int j = 0;

                    if (model2.getValueAt(i, j) == null) {
                        model2.setValueAt("W", i, j);
                        model3.setValueAt("W", i, j);
                        model4.setValueAt("W", i, j);
                        matriz[i][j] = g;
                        jTableCharacters.locate(i, j).setForeground(Color.RED);
                        player1.waterCharactersList.add(g);
                    } else if (model2.getValueAt(i2, j) == null) {
                        model2.setValueAt("W", i2, j);
                        model3.setValueAt("W", i2, j);
                        model4.setValueAt("W", i2, j);
                        matriz[i2][j] = g;
                        jTableCharacters.locate(i2, j).setForeground(Color.RED);
                        player1.waterCharactersList.add(g);
                    } else if (model2.getValueAt(i3, j) == null) {
                        model2.setValueAt("W", i3, j);
                        model3.setValueAt("W", i3, j);
                        model4.setValueAt("W", i3, j);
                        matriz[i3][j] = g;
                        jTableCharacters.locate(i3, j).setForeground(Color.RED);
                        player1.waterCharactersList.add(g);
                    }
                }
            }
        }
        if (UserLogin.Methods.ReturnChacarterWind(Name) != null) {
            if (player2.windCharactersList.contains(UserLogin.Methods.ReturnChacarterWind(Name))) {
                JOptionPane.showMessageDialog(null, "It have player 2");
                return;
            } else {
                if (player1.windCharactersList.contains(UserLogin.Methods.ReturnChacarterWind(Name))) {
                    JOptionPane.showMessageDialog(null, "It have player 1");
                    return;
                } else {
                    WindCharacter g = UserLogin.Methods.ReturnChacarterWind(Name);

                    int i = 3;
                    int i2 = 4;
                    int i3 = 5;
                    int j = 0;

                    if (model2.getValueAt(i, j) == null) {
                        model2.setValueAt("C", i, j);
                        model3.setValueAt("C", i, j);
                        model4.setValueAt("C", i, j);
                        matriz[i][j] = g;
                        jTableCharacters.locate(i, j).setForeground(Color.RED);
                        player1.windCharactersList.add(g);
                    } else if (model2.getValueAt(i2, j) == null) {
                        model2.setValueAt("C", i2, j);
                        model3.setValueAt("C", i2, j);
                        model4.setValueAt("C", i2, j);
                        matriz[i2][j] = g;
                        jTableCharacters.locate(i2, j).setForeground(Color.RED);
                        player1.windCharactersList.add(g);
                    } else if (model2.getValueAt(i3, j) == null) {
                        model2.setValueAt("C", i3, j);
                        model3.setValueAt("C", i3, j);
                        model4.setValueAt("C", i3, j);
                        matriz[i3][j] = g;
                        jTableCharacters.locate(i3, j).setForeground(Color.RED);
                        player1.windCharactersList.add(g);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (player1.fireCharactersList.size() + player1.groundCharactersList.size() + player1.waterCharactersList.size() + player1.windCharactersList.size() >= 3) {
            if (player2.fireCharactersList.size() + player2.groundCharactersList.size() + player2.waterCharactersList.size() + player2.windCharactersList.size() >= 3) {
                jPanel3.hide();
                jPanel2.show();
            } else {
                JOptionPane.showMessageDialog(null, "Player 2 doesn't have the 3 characters");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Player 1 doesn't have the 3 characters");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel) jTableCharacters.getModel();
        DefaultTableModel model3 = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel model4 = (DefaultTableModel) jTablePlay.getModel();

        String Name = jComboBox2.getSelectedItem() + "";

        if (UserLogin.Methods.ReturnChacarterGround(Name) != null) {
            if (player1.groundCharactersList.contains(UserLogin.Methods.ReturnChacarterGround(Name))) {
                JOptionPane.showMessageDialog(null, "It have player 1");
                return;
            } else {
                if (player2.groundCharactersList.contains(UserLogin.Methods.ReturnChacarterGround(Name))) {
                    JOptionPane.showMessageDialog(null, "It have player 2");
                    return;
                } else {
                    GroundCharacter g = UserLogin.Methods.ReturnChacarterGround(Name);

                    int i = 3;
                    int i2 = 4;
                    int i3 = 5;
                    int j = 9;

                    if (model2.getValueAt(i, j) == null) {
                        model2.setValueAt("G", i, j);
                        model3.setValueAt("G", i, j);
                        model4.setValueAt("G", i, j);
                        matriz[i][j] = g;
                        jTableCharacters.locate(i, j).setForeground(Color.RED);
                        player2.groundCharactersList.add(g);
                    } else if (model2.getValueAt(i2, j) == null) {
                        model2.setValueAt("G", i2, j);
                        model3.setValueAt("G", i2, j);
                        model4.setValueAt("G", i2, j);
                        matriz[i2][j] = g;
                        jTableCharacters.locate(i2, j).setForeground(Color.RED);
                        player2.groundCharactersList.add(g);
                    } else if (model2.getValueAt(i3, j) == null) {
                        model2.setValueAt("G", i3, j);
                        model3.setValueAt("G", i3, j);
                        model4.setValueAt("G", i3, j);
                        matriz[i3][j] = g;
                        jTableCharacters.locate(i3, j).setForeground(Color.RED);
                        player2.groundCharactersList.add(g);
                    }
                }
            }
        }
        if (UserLogin.Methods.ReturnChacarterFire(Name) != null) {
            if (player1.fireCharactersList.contains(UserLogin.Methods.ReturnChacarterFire(Name))) {
                JOptionPane.showMessageDialog(null, "It have player 1");
                return;
            } else {
                if (player2.fireCharactersList.contains(UserLogin.Methods.ReturnChacarterFire(Name))) {
                    JOptionPane.showMessageDialog(null, "It have player 2");
                    return;
                } else {
                    FireCharacter g = UserLogin.Methods.ReturnChacarterFire(Name);

                    int i = 3;
                    int i2 = 4;
                    int i3 = 5;
                    int j = 9;

                    if (model2.getValueAt(i, j) == null) {
                        model2.setValueAt("F", i, j);
                        model3.setValueAt("F", i, j);
                        model4.setValueAt("F", i, j);
                        matriz[i][j] = g;
                        jTableCharacters.locate(i, j).setForeground(Color.RED);
                        player2.fireCharactersList.add(g);
                    } else if (model2.getValueAt(i2, j) == null) {
                        model2.setValueAt("F", i2, j);
                        model3.setValueAt("F", i2, j);
                        model4.setValueAt("F", i2, j);
                        matriz[i2][j] = g;
                        jTableCharacters.locate(i2, j).setForeground(Color.RED);
                        player2.fireCharactersList.add(g);
                    } else if (model2.getValueAt(i3, j) == null) {
                        model2.setValueAt("F", i3, j);
                        model3.setValueAt("F", i3, j);
                        model4.setValueAt("F", i3, j);
                        matriz[i3][j] = g;
                        jTableCharacters.locate(i3, j).setForeground(Color.RED);
                        player2.fireCharactersList.add(g);
                    }
                }
            }
        }
        if (UserLogin.Methods.ReturnChacarterWater(Name) != null) {
            if (player1.waterCharactersList.contains(UserLogin.Methods.ReturnChacarterWater(Name))) {
                JOptionPane.showMessageDialog(null, "It have player 1");
                return;
            } else {
                if (player2.waterCharactersList.contains(UserLogin.Methods.ReturnChacarterWater(Name))) {
                    JOptionPane.showMessageDialog(null, "It have player 2");
                    return;
                } else {
                    WaterCharacter g = UserLogin.Methods.ReturnChacarterWater(Name);

                    int i = 3;
                    int i2 = 4;
                    int i3 = 5;
                    int j = 9;

                    if (model2.getValueAt(i, j) == null) {
                        model2.setValueAt("W", i, j);
                        model3.setValueAt("W", i, j);
                        model4.setValueAt("W", i, j);
                        matriz[i][j] = g;
                        jTableCharacters.locate(i, j).setForeground(Color.RED);
                        player2.waterCharactersList.add(g);
                    } else if (model2.getValueAt(i2, j) == null) {
                        model2.setValueAt("W", i2, j);
                        model3.setValueAt("W", i2, j);
                        model4.setValueAt("W", i2, j);
                        matriz[i2][j] = g;
                        jTableCharacters.locate(i2, j).setForeground(Color.RED);
                        player2.waterCharactersList.add(g);
                    } else if (model2.getValueAt(i3, j) == null) {
                        model2.setValueAt("W", i3, j);
                        model3.setValueAt("W", i3, j);
                        model4.setValueAt("W", i3, j);
                        matriz[i3][j] = g;
                        jTableCharacters.locate(i3, j).setForeground(Color.RED);
                        player2.waterCharactersList.add(g);
                    }
                }
            }
        }
        if (UserLogin.Methods.ReturnChacarterWind(Name) != null) {
            if (player1.windCharactersList.contains(UserLogin.Methods.ReturnChacarterWind(Name))) {
                JOptionPane.showMessageDialog(null, "It have player 1");
                return;
            } else {
                if (player2.windCharactersList.contains(UserLogin.Methods.ReturnChacarterWind(Name))) {
                    JOptionPane.showMessageDialog(null, "It have player 2");
                    return;
                } else {
                    WindCharacter g = UserLogin.Methods.ReturnChacarterWind(Name);

                    int i = 3;
                    int i2 = 4;
                    int i3 = 5;
                    int j = 9;

                    if (model2.getValueAt(i, j) == null) {
                        model2.setValueAt("C", i, j);
                        model3.setValueAt("C", i, j);
                        model4.setValueAt("C", i, j);
                        matriz[i][j] = g;
                        jTableCharacters.locate(i, j).setForeground(Color.RED);
                        player2.windCharactersList.add(g);
                    } else if (model2.getValueAt(i2, j) == null) {
                        model2.setValueAt("C", i2, j);
                        model3.setValueAt("C", i2, j);
                        model4.setValueAt("C", i2, j);
                        matriz[i2][j] = g;
                        jTableCharacters.locate(i2, j).setForeground(Color.RED);
                        player2.windCharactersList.add(g);
                    } else if (model2.getValueAt(i3, j) == null) {
                        model2.setValueAt("C", i3, j);
                        model3.setValueAt("G", i3, j);
                        model4.setValueAt("G", i3, j);
                        matriz[i3][j] = g;
                        jTableCharacters.locate(i3, j).setForeground(Color.RED);
                        player2.windCharactersList.add(g);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (java.lang.Character.isAlphabetic(c)) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You can't put letters");
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (java.lang.Character.isAlphabetic(c)) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You can't put letters");
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (java.lang.Character.isAlphabetic(c)) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You can't put letters");
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (java.lang.Character.isAlphabetic(c)) {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "You can't put letters");
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        MenuInterface.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        UserLogin.Methods.clearAll();
        UsersBackup.getArenas().clear();
        matriz = new Object[10][10];
        player1.getFireCharactersList().clear();
        player1.getGroundCharactersList().clear();
        player1.getWaterCharactersList().clear();
        player1.getWindCharactersList().clear();
        player1.getTowersList().clear();
        player2.getFireCharactersList().clear();
        player2.getGroundCharactersList().clear();
        player2.getWaterCharactersList().clear();
        player2.getWindCharactersList().clear();
        player2.getTowersList().clear();
        jPanel1.show();
        jPanel3.hide();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    public static final javax.swing.JComboBox<String> jComboBox1 = new javax.swing.JComboBox<>();
    public static final javax.swing.JComboBox<String> jComboBox2 = new javax.swing.JComboBox<>();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static final javax.swing.JTable jTable2 = new javax.swing.JTable();
    public static javax.swing.JTable jTableCharacters;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
